CREATE ROLE platform_api LOGIN;
CREATE DATABASE platform_api OWNER platform_api;
CREATE ROLE portfolio_risk LOGIN;
CREATE DATABASE portfolio_risk OWNER portfolio_risk;
CREATE ROLE trade_execution LOGIN;
CREATE DATABASE trade_execution OWNER trade_execution;
CREATE ROLE historical_replay LOGIN;
CREATE DATABASE historical_replay OWNER historical_replay;
CREATE ROLE decision_governance LOGIN;
CREATE DATABASE decision_governance OWNER decision_governance;
CREATE ROLE quant_research LOGIN;
CREATE DATABASE quant_research OWNER quant_research;
CREATE ROLE market_data LOGIN;
CREATE DATABASE market_data OWNER market_data;
